### ISSUE TITLE
Feature request: Ability to record the current track in MP3

### ISSUE THREAD

**Issue by Zeioth** [ebruck/radiotray-ng#117]
Sometimes you listen this really cool song on the radio and you just wanna click the record button to keep it. Even a simple implementation would be valuable.

**Comment by ebruck** [comment]
Does sound like a neat feature, but it's not really what I had in mind for radiotray-ng. I like to keep the app. as simple as possible, which is why I wrote no plugin system or a built in station editor. 

What I can do is expose the playing station's url through a dbus request. Using that you can launch a script to run streamripper.

**Comment by Zeioth** [comment]
Thank you! I will try it later and report.
