### ISSUE TITLE
compile on rhel distros

### ISSUE THREAD

**Issue by brumle80** [ebruck/radiotray-ng#12]
any chance you could add any pointers/fixes so this compiles on other distros than ubuntu?
struggling with make failing

I'm trying to get it to compile on Fedora 25

**Comment by ebruck** [comment]
Actually that is my next target. I've got it compiling on Fedora 26, but the appindicator support isn't working quite right (crashes). It could be related to me not using the latest gtk3 appindicator library. I've ported my gui code to gtk3, but threading support has changed and some functions I've used are deprecated and no longer work.  I'm going to look at removing the threading since I really don't need it.

**Comment by ebruck** [comment]
I just tried it (v0.1.5) on Fedora 25 and could get it to work this time.

Perhaps it was Fedora 26 that was the problem. One thing that is not working for me is the appindicator extension. It's not showing the submenu items (works fine on Ubuntu GNOME 17.04). GNOME's built in support shows the menu and I could play fine after installing all the gstreamer libraries.

Here are the libraries I used:

libcurl-devel
libbsd-devel
libnotify-devel
jsoncpp-devel
libxdg-basedir-devel
libappindicator-devel
gstreamer-devel
boost-devel
gstreamer1-devel

Please give it a go.

**Comment by ebruck** [comment]
Actually it is working fine. It appears that I hit some bug that prevents extension menus from expanding when displayed on a low resolution screen. The menu "just" fit on the screen before trying to open a group.

**Comment by brumle80** [comment]
thanks, will try again :)

**Comment by brumle80** [comment]
can confirm that it worked perfectly :)
I was missing one of the dependencies and had an error in the cmake command.
I am now running radiotray-ng without issue on Fedora 25, thanks for the help 👍
