### ISSUE TITLE
[enhancement] Automated change of radio station

### ISSUE THREAD

**Issue by al-right** [ebruck/radiotray-ng#122]
Hi Ed :)

Again a big thanks for a great application!

I have a suggestion for an enhancement - likely a plugin like the Sleep Timer:

**Request for enhancement**
Let Radio Tray NG:
1) change channel automatically at a specific time of day from radio channel A to channel B
2) change back to channel A (from B) when a specific period of time has passed
Basically what is needed is some sort of scheduler/planner where it is possible to select:
* Have a list of scheduled events (with add and remove button) and per event have:
* Radio station
* Start time
* Duration or End time
* Optional: Selection (e.g. radio button) specifying to either use 1) duration/end time or 2) stay on channel to continue listening indefinitely until other 'user intervention' ('interaction') or scheduled change would happen.

**Background**
Often I catch myself forgetting to change to the radio news (channel B) when they appear at noon / 12 o clock (or other times during the day.) Often the news last for 5 minutes or maybe 20 minuttes (when it is about the news at noon.) Therefore it would be nice if radio tray ng could change from station A to the other station B and once the news are done change back on its own to the usual/other radio program that plays music.

Thanks for listening :)

**Comment by Swipe650** [comment]
Hi, I do similar to this to mute the commercials on talk radio stations. This can all be done easily via a bash script using the radiotray-ng dbus commands.

**Comment by ebruck** [comment]
To me a scheduler would duplicate and be inferior to using cron which is why I have no plans on adding one. Same as @Swipe650 I use cron to start/stop playing certain stations. Please have a look at the dbus interface. Much more can be done by writing a bash script and examining if needed current playing meta data. There are several scripts under: https://github.com/ebruck/radiotray-ng/tree/master/src/radiotray-ng/extras/scripts
