### ISSUE TITLE
System play and pause buttons are not captured

### ISSUE THREAD

**Issue by aleksandergabriel** [ebruck/radiotray-ng#164]
I have Ubuntu 20.04 and in the old RadioTray I could pause and play radio playback using keyboard shortcuts. However at the moment RadioTray-ng does not respond to those commands. 
Is this feature missing in this version or is there a bug?

Best regards
Ales

**Comment by ebruck** [comment]
I don't believe there is much I can do since an appindicator never regains any sort of focus, which would allow it to grab the media keys again.  In my case Chrome tends to be the one holding on to the media keys. If I exit it then it starts working again. I've given up and just assign a few keys on my Microsoft 4000 to dbus commands for play/stop etc.

**Comment by aleksandergabriel** [comment]
Could you share dbus commands.

**Comment by ebruck** [comment]
https://github.com/ebruck/radiotray-ng#dbus-interface
