### ISSUE TITLE
Separators in bookmarks.

### ISSUE THREAD

**Issue by TomaszGasior** [ebruck/radiotray-ng#19]
Please, add ability to place separator between bookmarks items.

**Comment by ebruck** [comment]
I've resisted doing this, because under Gnome desktop (which I use) menus are rather large and it seems to have problems rendering if it won't fit on the screen. In fact I've added an option to the config that turns off the separators I do use. I realize that some users may not be running Gnome and won't suffer from this issue.

**Comment by TomaszGasior** [comment]
I mean about separator as menu element. User could add separator in the same way as radiostation — as group element; by editing bookmarks.json file or, in the future, by GUI. 

To be honest, this feature is not important. I wrote this issue because original RT had this feature.

**Comment by ebruck** [comment]
I was the one who put it in the original Radiotray. :-)

**Comment by ebruck** [comment]
I don't plan to add this.
