### ISSUE TITLE
rt2rtng does't convert correcty nested bookmarks

### ISSUE THREAD

**Issue by Wasnix** [ebruck/radiotray-ng#31]
rt2rtng does't convert nested bookmarks from old radiotray. The nesting structure disappers. All radio stations are on root level. 

I've thousands of radio stations arranged by country, state, city,...etc. rt2rtng puts all radio stations on top of the converted list, only keeping streams of same stations in single groups.

**Comment by ebruck** [comment]
The README.md mentions this:

> The rt2rtng script will convert your RadioTray bookmarks.xml file. All groups within groups are moved to the root and any empty ones are removed. It's not a perfect conversion and will no doubt require some editing.

This is by design. I chose not to support sub menus. It makes it harder to write a proper visual editor (which is nearly done) and I felt for myself at least that it was not really how radiotray-ng should be used. That amount of bookmarks is more than a simple tray app. should manage/display. Now having said that I may revisit this in the future, but I'm seeing system like gnome not handling large menus very well.

I should mention that I regretted adding it to the original radiotray as I've seen some wildly unusable bookmark layouts with hundreds of stations and dozens of sub menus.
