### ISSUE TITLE
[Archlinux] libboost - 1.64.0 not found 

### ISSUE THREAD

**Issue by ljoli** [ebruck/radiotray-ng#35]
Hello,

I use radiotray-ng for listen some web radio.
But when i update my distribution, I have an error : 
>> radiotray-ng 
radiotray-ng: error while loading shared libraries: libboost_filesystem.so.1.64.0: cannot open shared object file: No such file or directory

How can I fixe it ?

**Comment by ebruck** [comment]
Where did you get the binary and what distro are you using?

**Comment by ljoli** [comment]
Hi ,
@ebruck : I use Archlinux : 
>> uname -a
Linux ljj-pc 4.13.5-1-ARCH #1 SMP PREEMPT Fri Oct 6 09:58:47 CEST 2017 x86_64 GNU/Linux

So, i use the following version : 
https://aur.archlinux.org/packages/radiotray-ng
radiotray-ng   0.1.8-1

**Comment by ljoli** [comment]
I notice on my system : 

> ls -chl libboost_fil*
-rw-r--r-- 1 root root 265K Sep 24 21:32 libboost_filesystem.a
lrwxrwxrwx 1 root root   29 Sep 24 21:32 libboost_filesystem.so -> libboost_filesystem.so.1.65.1
-rwxr-xr-x 1 root root 106K Sep 24 21:32 libboost_filesystem.so.1.65.1

**Comment by ebruck** [comment]
Looks like the dependency isn't set correctly.
I believe this is it:  https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=radiotray-ng

It just lists "boost-libs":

depends=('boost-libs' 'curl' 'gstreamer' 'jsoncpp' 'libappindicator-gtk3'
         'libbsd' 'libnotify' 'libxdg-basedir' 'glibmm')

For Ubuntu my packaging specifies the version that it was compiled with. Perhaps that is the problem here.

**Comment by ljoli** [comment]
Yes, you are right. It is necessary to say the boost-libs version.

Thanks
