### ISSUE TITLE
Volume increase with play on.

### ISSUE THREAD

**Issue by Docdez** [ebruck/radiotray-ng#42]
Hello!

The app settings is default. Everytime with play it the general volume level is increased to maximum (it was painful) and volume level for other apps are not changed.

OS was upgraded one week ago, before it. I not modified the app (update).
I got this trouble after the Viber messenger installation (it removed already).

- Work with the "volume-level" parameter not helped.
- Work with the pulseaudio settings (with my small knowledge) not helped.

Can you give a advice about it problem?

The OS:
Debian 9
Linux varicap 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
MATE Desktop Environment 1.16.2

Thanks.

**Comment by ebruck** [comment]
This may be related to how pulse audio is configured. 
Have a look at issue #32.

**Comment by Docdez** [comment]
Yes, it issue is similar to my. I will try to use it consideration. I am sorry for the duplicate.

**Comment by stucki** [comment]
I think this should be reopened. For me the main quesiton is, how does it behave on a new system?
Just did so and the volume goes up after every channel switch. Do you really expect every user to change their PulseAudio configuration? IMO it's clearly a bug that must be fixed in here!

**Comment by ebruck** [comment]
@stucki I don't expect anything from any user of radiotray-ng. The bug was specific to how "**flat-volumes**" was configured. If you are using 18.04 then you "shouldn't'" be encountering that configuration.

I've gone over the code and yes radiotray-ng resets the volume level for each station as you change them, but it is using the level saved in the config. Are you by any chance changing the volume using pavucontrol or the settings app?

**Comment by stucki** [comment]
@ebruck My Ubuntu 18.04 is default, I didn't make any changes to the Pulseaudio configuration.

However, yes, I'm using pavucontrol to change my volume. Is there anything wrong with that? After all that's exactly the purpose of it: Changing volumes without having them restored by applications.

What is the purpose behind resetting the volume level for each station as you write above? As far as I can see, other programs don't do this, no?

**Comment by ebruck** [comment]
Radiotry-ng allows you to adjust the volume using the mouse over the tray icon and through dbus messages. Changing it outside of the app. throws off the internal tracking it is doing, which is why you see a sudden jump to the default of 100%. You can see the same behaviour in apps like Rhythmbox, but the difference is they don't reset it to last saved value on startup.

Anyways, I came up with a fix that should be able to detect the change and ensure that radiotray-ng is tracking with the new value. It's in my dev branch for v0.2.7  https://github.com/ebruck/radiotray-ng/commit/c53c15ac5f43b22a918ac49a924600cb8ebcf8d6 if you want to try it out.

**Comment by stucki** [comment]
@ebruck Thanks a lot for your feedback. Sounds great that there is a fix to this problem now!

What I don't understand why you're doing auto-detection now and not just leave the volume untouched until the user actively changes it (by scrolling over the icon as you mentioned it, or just using any external program). What is this internal tracking that you just mentioned?

**Comment by ebruck** [comment]
Because the volume level I display in the menu will be wrong and what is saved to the config will also be incorrect. Most people don't use with pavucontrol and use the built in volume control.

**Comment by stucki** [comment]
@ebruck Thanks for the clarification!
