### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by sasa1984** [ebruck/radiotray-ng#53]
Is it possible to translate radiotray-ng?

**Comment by lulcat** [comment]
I know quite a few of languages but not writing as a native :p of those unfortunately English and Norwegian are probably the only ones. But I can do the Norwegian IF internationalisation is ready (placemarkers for the translatable strings etc.); also I can do it in return for being able to bloody adjust the volume within app! So far it only displays volume from master... I use alsa only and I can set up another softvol possibly but on a radio app of all things.. come on. ^^
Kinda silly calling someone else's project for 'next generation' and not being able to do that even.

**Comment by lulcat** [comment]
Heya.. no I  don't use pulse.. and it's very nice.. _except_ I can't control one thing.. this app except through the master volume of course... because it doesn't have a way to adjust it's own volume it seems.. on my system, it just displays 93% greyed out... maybe it's my system? Can you adjust the volume in the radiotray app? If so, then of course, my apologies for saying it was the app not being bale to do something that basic as a sound providing app!

**Comment by ebruck** [comment]
Have you tried the scroll wheel on the icon? What desktop environment are you using? 

If you DE doesn't have full appindcator support then there isn't much I can do. You can also control the volume through the dbus interface. Perhaps you can assign qdus commands to a hotkey.

```
$ qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.volume_up
$ qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.volume_down
```

**Comment by lulcat** [comment]
I use pure alsa and I can control mplayer independendtly of master volume, and of course any other item which has it's own internal volume slider, eg. youtube, browser, mplayer (had to enable with config option), so ye, the only item remaining is this app.. as I understood, the app was a bit in its infancy so to speak, so I just assumed the lack of controlling volume was due to that, but if it is somehow my system not working correctly then I can figure out why (and do the Norwegian for you ,p).

**Comment by lulcat** [comment]
"bookmarks" : "/home/<user>/.config/radiotray-ng/bookmarks.json",
   "last-station" : "Groove Salad",
   "last-station-group" : "Chill",
   "last-station-notifications" : true,
   "notification-verbose" : true,
   "notifications" : true,
   "split-title" : true,
   "volume-level" : 94

was the original file, removing it, created this one:

"bookmarks" : "/home/<user>/.config/radiotray-ng/bookmarks.json",
   "notification-verbose" : true,
   "notifications" : true,
   "split-title" : true,
   "volume-level" : 100

and ifnally yoursa wiht all the options , including volume step, is what made me figure out the 'issue': 

and I ddn't see your comment until after I had posted. Have a nice one. x

**Comment by glixx** [comment]
Will you use transifex for translations? It's free for open-source projects.

**Comment by zen2** [comment]
I can help to translate for French langage.

**Comment by vinzv** [comment]
Transifex would be okay, but Weblate is way better in terms of responsiveness and speed: https://weblate.org/en/hosting/

**Comment by glixx** [comment]
Support of weblate is too stupid and translations live own life without sense. Transifex works the best.

**Comment by vinzv** [comment]
Whatever, I hardly care as long as the strings are available for translation somewhere.

**Comment by oddmean** [comment]
I can help with Russian translation. How could I do it?

**Comment by tassoman** [comment]
I can put in Italian language if you're interested :it:

**Comment by felipefm** [comment]
I make myself available, to translate into Brazilian Portuguese
