### ISSUE TITLE
Several improvement...

### ISSUE THREAD

**Issue by rcspam** [ebruck/radiotray-ng#8]
Hi and very much thanks for this works...
1/ To have radiotray-ng behavior like original radiotray, is it possible to start playing with middle click?
2/ Volume increment with mouse wheel is too small, is possible to increase it, pehaps with a number in the config file.
3/ I can't set subgroup in bookmark.json, it's me or it's not coded?
Voila

Yet thanks.
Best regards

**Comment by ebruck** [comment]
1. I'll look into it. Perhaps I'll add it to the next release. See branch v0.1.5 for other changes.
2. I can add that. I'l make it configurable like RadioTray.
3. This is by design. I originally implemented that for RadiotTray, but found it can lead to nasty cascading menus and a more complex bookmark editor.

**Comment by ebruck** [comment]
a680452ac6c55c8e7fb259e75d8869c57bac65a6 adds volume step support.

**Comment by rcspam** [comment]
Thanks....
1/.. It is very strange, especially since the wheel mouse signals are supported... :(

**Comment by rcspam** [comment]
... 3/ It could be easier to adapt original python code to create your bookmark editor....
Yet thanks...

**Comment by ebruck** [comment]
I chose JSON, because I dislike XML and the old bookmark format is flawed. It has issues with group/station names needing to be unique.

If you have a bookmark file that you want to use, then wait for the next release or pull down the v0.1.5 branch. There is a new rt2rtng script that converts old xml bookmarks.

**Comment by rcspam** [comment]
Great news, i have create my own from old radiotray xml by hand, it a long work... 
I have test it works well (subgroup to group are ok), it could be cool to coded subgroup, but it's your choice...
Big Thanks
